background_color: white
cycle_time: 10
feeds:
- https://www.techrepublic.com/rssfeeds/articles/
- https://xkcd.com/rss.xml
- http://newsrss.bbc.co.uk/rss/newsonline_world_edition/americas/rss.xml
font_color:
- '#000000'
font_size:
- 12pt
font_type:
- Times New Roman
window placement: top left
