background_color: powder blue
cycle_time: 30
feeds:
<<<<<<< HEAD
- AReallyFakeFeed
- AnEvenFakerFeed
font_color: black
font_size: 12
font_type: Times
window placement: top right
=======
- https://www.techrepublic.com/rssfeeds/articles/
- https://xkcd.com/rss.xml
- http://newsrss.bbc.co.uk/rss/newsonline_world_edition/americas/rss.xml
>>>>>>> feature/eesha
